export interface ToolParam {
  name: string;
  label: string;
  type: 'text' | 'select' | 'number' | 'password' | 'color';
  options?: { value: string; label: string }[];
  defaultValue?: string | number;
  placeholder?: string;
}

export interface Tool {
  slug: string;
  name: string;
  description: string;
  icon: string;
  color: string;
  bgColor: string;
  borderColor: string;
  category: string;
  apiEndpoint: string;
  multipleFiles: boolean;
  inputLabel: string;
  acceptedFormats: string;
  outputFormat: string;
  outputMime: string;
  params?: ToolParam[];
}

export const CATEGORIES = [
  // { id: 'organize',   label: 'Merge, Split & Organize', color: '#3b82f6', icon: '🔀' },
  // { id: 'optimize',   label: 'Document Optimization',   color: '#06b6d4', icon: '⚡' },
  { id: 'to-pdf',     label: 'Convert TO PDF',          color: '#22c55e', icon: '⬆️' },
  { id: 'from-pdf',   label: 'Convert FROM PDF',        color: '#16a34a', icon: '⬇️' },
  // { id: 'edit',       label: 'Content Editing',         color: '#f97316', icon: '✏️' },
  // { id: 'security',   label: 'Security & Sign',         color: '#ef4444', icon: '🔒' },
  // { id: 'standards',  label: 'Technical Standards',     color: '#eab308', icon: '🏅' },
];

export const TOOLS: Tool[] = [
  // ─── Merge, Split & Organize ───────────────────────────────────────────────
  {
    slug: 'merge',
    name: 'Merge PDF',
    description: 'Combine multiple PDF files into one single document',
    icon: '🔀',
    color: '#3b82f6',
    bgColor: '#eff6ff',
    borderColor: '#bfdbfe',
    category: 'organize',
    apiEndpoint: '/pdf/merge',
    multipleFiles: true,
    inputLabel: 'Select PDF files to merge',
    acceptedFormats: '.pdf',
    outputFormat: 'merged.pdf',
    outputMime: 'application/pdf',
  },
  {
    slug: 'split',
    name: 'Split PDF',
    description: 'Split a PDF into separate pages or page ranges',
    icon: '✂️',
    color: '#3b82f6',
    bgColor: '#eff6ff',
    borderColor: '#bfdbfe',
    category: 'organize',
    apiEndpoint: '/pdf/split',
    multipleFiles: false,
    inputLabel: 'Select PDF to split',
    acceptedFormats: '.pdf',
    outputFormat: 'split.zip',
    outputMime: 'application/zip',
    params: [
      {
        name: 'split_mode',
        label: 'Split Mode',
        type: 'select',
        options: [
          { value: 'ranges', label: 'By Page Ranges' },
          { value: 'fixed_range', label: 'Every N Pages' },
          { value: 'remove_pages', label: 'Remove Pages' },
        ],
        defaultValue: 'ranges',
      },
      { name: 'ranges', label: 'Page Ranges (e.g. 1-3, 5)', type: 'text', defaultValue: '1-999', placeholder: '1-3, 5' },
      { name: 'fixed_range', label: 'Pages per split', type: 'number', defaultValue: 1 },
    ],
  },
  // ─── Document Optimization ────────────────────────────────────────────────
  {
    slug: 'compress',
    name: 'Compress PDF',
    description: 'Reduce PDF file size while maintaining quality',
    icon: '🗜️',
    color: '#06b6d4',
    bgColor: '#ecfeff',
    borderColor: '#a5f3fc',
    category: 'optimize',
    apiEndpoint: '/pdf/compress',
    multipleFiles: false,
    inputLabel: 'Select PDF to compress',
    acceptedFormats: '.pdf',
    outputFormat: 'compressed.pdf',
    outputMime: 'application/pdf',
    params: [
      {
        name: 'compression_level',
        label: 'Compression Level',
        type: 'select',
        options: [
          { value: 'low', label: 'Low (better quality)' },
          { value: 'recommended', label: 'Recommended (balanced)' },
          { value: 'extreme', label: 'Extreme (smallest size)' },
        ],
        defaultValue: 'recommended',
      },
    ],
  },
  {
    slug: 'rotate',
    name: 'Rotate PDF',
    description: 'Rotate PDF pages to the correct orientation',
    icon: '🔄',
    color: '#06b6d4',
    bgColor: '#ecfeff',
    borderColor: '#a5f3fc',
    category: 'optimize',
    apiEndpoint: '/pdf/rotate',
    multipleFiles: false,
    inputLabel: 'Select PDF to rotate',
    acceptedFormats: '.pdf',
    outputFormat: 'rotated.pdf',
    outputMime: 'application/pdf',
    params: [
      {
        name: 'rotation',
        label: 'Rotation Degrees',
        type: 'select',
        options: [
          { value: '90',  label: '90° Clockwise' },
          { value: '180', label: '180°' },
          { value: '270', label: '270° (90° Counter-clockwise)' },
        ],
        defaultValue: '90',
      },
    ],
  },
  {
    slug: 'repair',
    name: 'Repair PDF',
    description: 'Fix corrupted or damaged PDF files',
    icon: '🔧',
    color: '#06b6d4',
    bgColor: '#ecfeff',
    borderColor: '#a5f3fc',
    category: 'optimize',
    apiEndpoint: '/pdf/repair',
    multipleFiles: false,
    inputLabel: 'Select PDF to repair',
    acceptedFormats: '.pdf',
    outputFormat: 'repaired.pdf',
    outputMime: 'application/pdf',
  },
  // ─── Convert TO PDF ────────────────────────────────────────────────────────
  {
    slug: 'word-to-pdf',
    name: 'Word to PDF',
    description: 'Convert Word documents (DOCX/DOC) to PDF format',
    icon: '📝',
    color: '#22c55e',
    bgColor: '#f0fdf4',
    borderColor: '#bbf7d0',
    category: 'to-pdf',
    apiEndpoint: '/pdf/office-to-pdf',
    multipleFiles: false,
    inputLabel: 'Select Word document',
    acceptedFormats: '.doc,.docx',
    outputFormat: 'converted.pdf',
    outputMime: 'application/pdf',
  },
  {
    slug: 'excel-to-pdf',
    name: 'Excel to PDF',
    description: 'Convert Excel spreadsheets (XLSX/XLS) to PDF format',
    icon: '📊',
    color: '#22c55e',
    bgColor: '#f0fdf4',
    borderColor: '#bbf7d0',
    category: 'to-pdf',
    apiEndpoint: '/pdf/office-to-pdf',
    multipleFiles: false,
    inputLabel: 'Select Excel file',
    acceptedFormats: '.xls,.xlsx',
    outputFormat: 'converted.pdf',
    outputMime: 'application/pdf',
  },
  {
    slug: 'ppt-to-pdf',
    name: 'PowerPoint to PDF',
    description: 'Convert PowerPoint presentations (PPTX/PPT) to PDF',
    icon: '📋',
    color: '#22c55e',
    bgColor: '#f0fdf4',
    borderColor: '#bbf7d0',
    category: 'to-pdf',
    apiEndpoint: '/pdf/office-to-pdf',
    multipleFiles: false,
    inputLabel: 'Select PowerPoint file',
    acceptedFormats: '.ppt,.pptx',
    outputFormat: 'converted.pdf',
    outputMime: 'application/pdf',
  },
  // {
  //   slug: 'image-to-pdf',
  //   name: 'Image to PDF',
  //   description: 'Convert JPG, PNG, TIFF images to PDF format',
  //   icon: '🖼️',
  //   color: '#22c55e',
  //   bgColor: '#f0fdf4',
  //   borderColor: '#bbf7d0',
  //   category: 'to-pdf',
  //   apiEndpoint: '/pdf/image-to-pdf',
  //   multipleFiles: true,
  //   inputLabel: 'Select images',
  //   acceptedFormats: '.jpg,.jpeg,.png,.tiff,.bmp,.gif',
  //   outputFormat: 'converted.pdf',
  //   outputMime: 'application/pdf',
  // },
  // {
  //   slug: 'html-to-pdf',
  //   name: 'HTML to PDF',
  //   description: 'Convert HTML files or web pages to PDF format',
  //   icon: '🌐',
  //   color: '#22c55e',
  //   bgColor: '#f0fdf4',
  //   borderColor: '#bbf7d0',
  //   category: 'to-pdf',
  //   apiEndpoint: '/pdf/html-to-pdf',
  //   multipleFiles: false,
  //   inputLabel: 'Select HTML file',
  //   acceptedFormats: '.html,.htm',
  //   outputFormat: 'converted.pdf',
  //   outputMime: 'application/pdf',
  // },
  // ─── Convert FROM PDF ──────────────────────────────────────────────────────
  {
    slug: 'pdf-to-image',
    name: 'PDF to JPG',
    description: 'Convert each PDF page to a JPG image (output as ZIP)',
    icon: '🖼️',
    color: '#16a34a',
    bgColor: '#f0fdf4',
    borderColor: '#86efac',
    category: 'from-pdf',
    apiEndpoint: '/pdf/pdf-to-image',
    multipleFiles: false,
    inputLabel: 'Select PDF to convert',
    acceptedFormats: '.pdf',
    outputFormat: 'images.zip',
    outputMime: 'application/zip',
  },
  {
    slug: 'extract',
    name: 'Extract Pages',
    description: 'Extract pages or images from a PDF as a ZIP archive',
    icon: '📤',
    color: '#16a34a',
    bgColor: '#f0fdf4',
    borderColor: '#86efac',
    category: 'from-pdf',
    apiEndpoint: '/pdf/extract',
    multipleFiles: false,
    inputLabel: 'Select PDF to extract from',
    acceptedFormats: '.pdf',
    outputFormat: 'extracted.zip',
    outputMime: 'application/zip',
    params: [
      {
        name: 'mode',
        label: 'Extract Mode',
        type: 'select',
        options: [
          { value: 'pages', label: 'Extract as individual PDF pages' },
          { value: 'images', label: 'Extract embedded images' },
        ],
        defaultValue: 'pages',
      },
    ],
  },
  // ─── Content Editing ───────────────────────────────────────────────────────
  {
    slug: 'watermark',
    name: 'Add Watermark',
    description: 'Add text watermark to PDF pages',
    icon: '💧',
    color: '#f97316',
    bgColor: '#fff7ed',
    borderColor: '#fed7aa',
    category: 'edit',
    apiEndpoint: '/pdf/watermark',
    multipleFiles: false,
    inputLabel: 'Select PDF to watermark',
    acceptedFormats: '.pdf',
    outputFormat: 'watermarked.pdf',
    outputMime: 'application/pdf',
    params: [
      { name: 'text', label: 'Watermark Text', type: 'text', defaultValue: 'CONFIDENTIAL', placeholder: 'Enter watermark text' },
      {
        name: 'vertical_position',
        label: 'Vertical Position',
        type: 'select',
        options: [
          { value: 'top', label: 'Top' },
          { value: 'middle', label: 'Middle' },
          { value: 'bottom', label: 'Bottom' },
        ],
        defaultValue: 'middle',
      },
      {
        name: 'horizontal_position',
        label: 'Horizontal Position',
        type: 'select',
        options: [
          { value: 'left', label: 'Left' },
          { value: 'center', label: 'Center' },
          { value: 'right', label: 'Right' },
        ],
        defaultValue: 'center',
      },
      { name: 'font_size', label: 'Font Size', type: 'number', defaultValue: 40 },
      { name: 'transparency', label: 'Transparency (0-100)', type: 'number', defaultValue: 50 },
      { name: 'rotation', label: 'Rotation (degrees)', type: 'number', defaultValue: -45 },
      { name: 'font_color', label: 'Color', type: 'color', defaultValue: '#FF0000' },
    ],
  },
  {
    slug: 'page-numbers',
    name: 'Add Page Numbers',
    description: 'Insert page numbers into your PDF document',
    icon: '#️⃣',
    color: '#f97316',
    bgColor: '#fff7ed',
    borderColor: '#fed7aa',
    category: 'edit',
    apiEndpoint: '/pdf/page-numbers',
    multipleFiles: false,
    inputLabel: 'Select PDF to number',
    acceptedFormats: '.pdf',
    outputFormat: 'numbered.pdf',
    outputMime: 'application/pdf',
    params: [
      { name: 'starting_number', label: 'Starting Number', type: 'number', defaultValue: 1 },
      {
        name: 'vertical_position',
        label: 'Position (Vertical)',
        type: 'select',
        options: [
          { value: 'top', label: 'Top' },
          { value: 'bottom', label: 'Bottom' },
        ],
        defaultValue: 'bottom',
      },
      {
        name: 'horizontal_position',
        label: 'Position (Horizontal)',
        type: 'select',
        options: [
          { value: 'left', label: 'Left' },
          { value: 'center', label: 'Center' },
          { value: 'right', label: 'Right' },
        ],
        defaultValue: 'center',
      },
      { name: 'font_size', label: 'Font Size', type: 'number', defaultValue: 12 },
      { name: 'font_color', label: 'Color', type: 'color', defaultValue: '#000000' },
    ],
  },
  {
    slug: 'ocr',
    name: 'OCR PDF',
    description: 'Make scanned PDFs searchable with Optical Character Recognition',
    icon: '🔍',
    color: '#f97316',
    bgColor: '#fff7ed',
    borderColor: '#fed7aa',
    category: 'edit',
    apiEndpoint: '/pdf/ocr',
    multipleFiles: false,
    inputLabel: 'Select scanned PDF',
    acceptedFormats: '.pdf',
    outputFormat: 'ocr.pdf',
    outputMime: 'application/pdf',
    params: [
      {
        name: 'language',
        label: 'Document Language',
        type: 'select',
        options: [
          { value: 'eng', label: 'English' },
          { value: 'spa', label: 'Spanish' },
          { value: 'fra', label: 'French' },
          { value: 'deu', label: 'German' },
          { value: 'por', label: 'Portuguese' },
          { value: 'ita', label: 'Italian' },
          { value: 'chi_sim', label: 'Chinese (Simplified)' },
          { value: 'ara', label: 'Arabic' },
        ],
        defaultValue: 'eng',
      },
    ],
  },
  // ─── Security & Sign ───────────────────────────────────────────────────────
  {
    slug: 'protect',
    name: 'Protect PDF',
    description: 'Password protect your PDF to restrict access',
    icon: '🔐',
    color: '#ef4444',
    bgColor: '#fef2f2',
    borderColor: '#fecaca',
    category: 'security',
    apiEndpoint: '/pdf/protect',
    multipleFiles: false,
    inputLabel: 'Select PDF to protect',
    acceptedFormats: '.pdf',
    outputFormat: 'protected.pdf',
    outputMime: 'application/pdf',
    params: [
      { name: 'password', label: 'Password', type: 'password', placeholder: 'Enter password', defaultValue: '' },
    ],
  },
  {
    slug: 'unlock',
    name: 'Unlock PDF',
    description: 'Remove password protection from a PDF file',
    icon: '🔓',
    color: '#ef4444',
    bgColor: '#fef2f2',
    borderColor: '#fecaca',
    category: 'security',
    apiEndpoint: '/pdf/unlock',
    multipleFiles: false,
    inputLabel: 'Select protected PDF',
    acceptedFormats: '.pdf',
    outputFormat: 'unlocked.pdf',
    outputMime: 'application/pdf',
    params: [
      { name: 'password', label: 'Current Password', type: 'password', placeholder: 'Enter current password', defaultValue: '' },
    ],
  },
  // ─── Technical Standards ───────────────────────────────────────────────────
  {
    slug: 'pdf-to-pdfa',
    name: 'PDF to PDF/A',
    description: 'Convert PDF to PDF/A format for long-term archiving',
    icon: '🏛️',
    color: '#eab308',
    bgColor: '#fefce8',
    borderColor: '#fef08a',
    category: 'standards',
    apiEndpoint: '/pdf/pdf-to-pdfa',
    multipleFiles: false,
    inputLabel: 'Select PDF to archive',
    acceptedFormats: '.pdf',
    outputFormat: 'converted_pdfa.pdf',
    outputMime: 'application/pdf',
  },
  {
    slug: 'validate-pdfa',
    name: 'Validate PDF/A',
    description: 'Check whether a PDF file is valid PDF/A compliant',
    icon: '✅',
    color: '#eab308',
    bgColor: '#fefce8',
    borderColor: '#fef08a',
    category: 'standards',
    apiEndpoint: '/pdf/validate-pdfa',
    multipleFiles: false,
    inputLabel: 'Select PDF to validate',
    acceptedFormats: '.pdf',
    outputFormat: 'validation.json',
    outputMime: 'application/json',
  },
];
